### ISSUE TITLE
Adding FindUsbgx.cmake script with exports as CMake support file

### ISSUE THREAD

**Issue by studiofuga** [linux-usb-gadgets/libusbgx#31]
The attached file is useful for use with CMake, since it checks for the library and exports the proper module `Usbgx::Usbgx`.

It should be installed in `${LIBDIR}/cmake/Usbgx`.
Hope it helps.

[FindUsbgx.cmake.txt](https://github.com/libusbgx/libusbgx/files/2473626/FindUsbgx.cmake.txt)

**Comment by kopasiak** [comment]
Nice one! How about adding this to repository and creating a suitable makefile target?

**Comment by studiofuga** [comment]
I'm not very familiar with autotools. But I'll try. Thanks.

**Comment by studiofuga** [comment]
Should I add an additional config option and a conditional test? Perhaps it can always be installed as for the pkgconfig file.

**Comment by kopasiak** [comment]
Well... yeah let's install it always. If there is anyone who is annoyed with that he will submit a patch;)

**Comment by studiofuga** [comment]
Well, I almost did it but I'm unable to fix the following issue:

I created a proper `LibUsbgxConfig.in` file that should generate `LibUsbgxConfig.cmake` and it makes use of `@libdir@` and `@includedir@` variables, but they expands to `${prefix}/include` and this cannot work. I need fully expanded variables.

Do you know how to do this?
Thanks

**Comment by kopasiak** [comment]
@pszewczyk you have some nice experience with autotools. Do you have any idea where the problem comes from?

**Comment by kopasiak** [comment]
BTW to simplify the debugging you can push the WIP code as pull request

**Comment by studiofuga** [comment]
Ok I'll do

**Comment by pabs3** [comment]
@studiofuga did you get the chance to reformat this as a pull request?

**Comment by studiofuga** [comment]
hi @pabs3 , my changes were already included in the project, see commit 664b7e6fe7f8269a774101d7625dd0a82c8aadd3 .
I'm not using the library in the project anymore so I can't tell if they work or not.

**Comment by pabs3** [comment]
@studiofuga I see, thanks for the info. I'm going to close this then, presumably it works and if it doesn't then someone will likely file a new issue about it.
