### ISSUE TITLE
Running Examples

### ISSUE THREAD

**Issue by icordova07** [linux-usb-gadgets/libusbgx#36]
After passing the second step outlined in the README file:

`gadget-acm-ecm`

 the following error is presented:

```
usbg_init()  No such file or directory: couldn't init gadget state

Error on USB gadget init
Error: USBG_ERROR_NOT_FOUND : Not found (file or directory removed)

```

How can this issue be resolved?

**Comment by kopasiak** [comment]
You probably don't have ConfigFS mounted and/or gadget subsystem loaded

**Comment by nmay231** [comment]
I'm not a very advanced user when it comes to this stuff, but this resolved my issue.

```
sudo modprobe g_ether configfs
```

**Comment by pabs3** [comment]
@icordova07 I've documented that the configfs Linux kernel module needs to be loaded, please let us know if that works or not for you.
