### ISSUE TITLE
License clarity?

### ISSUE THREAD

**Issue by karlp** [linux-usb-gadgets/libusbgx#70]
What's the actual license of this library please?  There's both GPL and LGPL copying files, but I can't find any explanation what is covered by each?

I'm _guessing_ the intent is library under lgpl and examples and docs under gpl? but guessing is never a good idea on licensing :)

**Comment by kopasiak** [comment]
Yes that's exactly how it is library - LGP and examples GPL. It should be mentioned in every file header. TBH I'd prefer to make examples MIT or sth more liberal but the original author of libusbg started it this way and I just continued.

**Comment by karlp** [comment]
It might be mentioned in every file header, but it's ..... not friendly, shall we say, to expect every user to look at every single source file to check.  Thanks for clarifying!

**Comment by pabs3** [comment]
Hopefully the new note in the README is clear enough?

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
