### ISSUE TITLE
how to find the gadget device file?

### ISSUE THREAD

**Issue by folkertvanheusden** [linux-usb-gadgets/libusbgx#77]
Hi,

When I create an UVC device, a /dev/video1 appears. How do I find that device file programmatically? I know that udev can signal this, but how do I then know that the newly created device is the one I just initialized and not some other by an other application?

**Comment by pabs3** [comment]
I don't know enough Linux USB gadget stuff to answer this properly,
but in the worst case you can always filter new devices to just the
ones that match exactly the one that you configured, inc serial num?

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by folkertvanheusden** [comment]
I was pointed at https://gitlab.freedesktop.org/camera/uvc-gadget/-/blob/master/lib/configfs.c#L199 so I'm going for that route.
